#!/bin/bash

echo "🚀 DemARK Jupyter Lab - Simple Commands"
echo "======================================="
echo ""

echo "✅ Here are the exact commands to run:"
echo ""
echo "1. Start the container:"
echo "   devcontainer up --workspace-folder ."
echo ""
echo "2. Start Jupyter Lab (in the container):"
echo "   docker exec -it \$(docker ps | grep vsc-demark | awk '{print \$1}') bash -c \"source /opt/conda/etc/profile.d/conda.sh && conda activate DemARK && jupyter lab --ip=0.0.0.0 --port=8890 --no-browser --allow-root --ServerApp.token='' --ServerApp.password='' --ServerApp.disable_check_xsrf=true\""
echo ""
echo "3. In a NEW terminal, forward the port:"
echo "   docker exec -it \$(docker ps | grep vsc-demark | awk '{print \$1}') socat TCP-LISTEN:8890,fork TCP:localhost:8890"
echo ""
echo "4. Open your browser to: http://localhost:8890"
echo ""
echo "🎉 That's it!" 