#!/bin/sh
wget -nv https://codeload.github.com/econ-ark/HARK/tar.gz/master
mv master lib
cd lib
tar -xzf master
rm master
jupyter contrib nbextension install --user
jupyter nbextension enable hide_input/main